name: CI
on: [push]

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12', '3.13']

        steps:
            - uses: actions/checkout@v3

            - name: Install poetry
              run: pipx install poetry

            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'poetry'

            - name: Install poetry packages
              run: poetry install --with dev

            - name: Run linting
              run: |
                  poetry run ruff format --check .
                  poetry run ruff check .

            - name: Cache mypy
              uses: actions/cache@v4
              id: cache-mypy
              with:
                  path: .mypy_cache
                  key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.python-version }}-${{ github.ref_name }}
                  restore-keys: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.python-version }}-main

            - name: Run mypy
              run: poetry run mypy . --config-file setup.cfg

            - name: Run pytest
              run: poetry run pytest -vv .
